version: '3.8'

services:
  app:
    container_name: express-app
    build: .
    restart: unless-stopped
    command: npm run start
    ports:
      - "3003:3003"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"