service: UserProfile
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:STAGE}
  region: us-east-1
  memorySize: 1769
  timeout: 30
functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true